language: node_js
node_js:
- '6'
cache:
  directories:
    - "node_modules"
    - "lib"
install:
- npm install
- npm install -g bower
- bower install
script: npm run eslint && npm run test:sl
dist: trusty
env:
  global:
  - secure: DIw9SFd7as3O50GQtHQEcP2T1BYEeyFT2I5rh1OeXFVaUSaZvh7nHIOqfwyc936q04hJx0D38zBEod6HfC+Q8fc903wxBEaZsLI96Pjc9yw3sYZtibFPjVxBiD6grPIcVHB21MXt5k1JUZBIlefc1xJ9z6+RI6Rfu+oTFapLpBnRpVWauDELKPx+pd2PRUrGE1QdeRL2f8W8jdzf3QjFVdqayYjiQ91E7WRPwSlLRlRbit5FAEtvOG0o9yeietj+Fxg6GIQgWqJOdltB7htyfuvJFeN386kleoXYXYI9SkQRsqu33rVcL+ZhPEVYiE8azQIsE+B7/bKSZgYtGOeDucH5OnzuKx9HqcWTa++yfb7nUoBPVijreuSzEltpdoZWmRw1lMHqBAO1tladqlxp3+zDzZZcA70PFSzfC8FBTzgfoavUVlQIlVJcSMH6bBkdf58T/x71wj7Oq+OJ7gAPaHUK4X+W6ONhnPYBZ63fn9XFLqRNAIpi3UmfWNDpg5J3tbKYdE6LBzpCjTaka0jjlYiFZnrNb6+inXz0IawKsib45HE5h0x73Sx3zeOEFXtM9acUHQdWvLKSTNEfB8kuYahN56VSJQIpp1HiS3F/NhRWFLQP2X6AvG+UCHpEuhi5UwEAVQ2vj85Zku0Bh1Mz84C50Q1OKAviSc7P0HfLKow=
  - secure: r8w85y7M37qv5dAY7xkxdLoblqTiJa6Q3NJ5VFv7cWfE/6t/o/ktEk2SjzGJH25+QrgdZ5MIGOkuVCVd8KJlkFPyp6f0fgyftVDGpWmzxQX9rOSprV8y+4aoEuG5AwhLwj2nHVSJ8xA50FT2UI4CHFoziUP2aOcwUlvckRnbX5VaeNls+WI1hmEDMiUS1LD8rDgwhDH8BRU+ly1lmevniJ2UNdqFOE7GrL9NmOCc/qjisO403q0jv3fP1P2TEs4coJmAyKl0flolLW2DfZqKH3RWppRJvoW8y3kOXPnLMjClwl6tGdNxTOvRE2FOKFU46Wzu6lieI0gVaZK/FHVG3RlIzYkgREHPp2VfS0mnMOhd3V5JihB5Cm6Pt2nYmEh/g9LF7eXS7b2enZRHZWIHDIrPaiR+VMmbqbKhYms5nZkjNeX1qDh3qLDQD+GfpRjio7oC+QIZm7Tzlz7GFcH31A8Z3Sp2Uamoidy6AI+kRLgrxu9muTIcBWro0bMNYx+7x8bt5l77Rl2yixFzthgaYd9MBWq4H8Cr4PltWvXGBW56okz/owzyoiRcD5IVpAOOBU3/Po3Kf00ZvX1x/Yq1kHxJmIqLxCZ7QwEUQOGIOZtN0EcuISHhCJrDtwjQ9RhKqzZQHZalEMnJQ6lD/U96Hjc3hAq6TY6hR4x9JfT5sns=
